# Generated by Django 5.2.16 on 2026-08-24 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferenceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user preference categories",
                "db_table": "user_preference_categories",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=False)),
                (
                    "school_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="school_level_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preferences",
                        to="events.schoollevel",
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
    ]
