# Generated by Django 5.2.16 on 2026-07-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["high_school", "college"]',
                    ),
                ),
                (
                    "preferred_locations",
                    models.JSONField(
                        blank=True, default=list, help_text='e.g. ["Nairobi", "Thika"]'
                    ),
                ),
                (
                    "max_days_ahead",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Only recommend events happening within this many days.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Combines academic subjects and activity types the student is interested in.",
                        related_name="preferred_by",
                        to="events.category",
                    ),
                ),
            ],
        ),
    ]
