# Generated by Django 5.2.16 on 2026-08-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("preferences", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpreferencecategory",
            name="category",
            field=models.ForeignKey(
                db_column="category_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference_links",
                to="events.category",
            ),
        ),
        migrations.AddField(
            model_name="userpreferencecategory",
            name="user_preference",
            field=models.ForeignKey(
                db_column="user_preference_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_links",
                to="preferences.userpreference",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="preferred_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_preferences",
                through="preferences.UserPreferenceCategory",
                to="events.category",
            ),
        ),
        migrations.AddIndex(
            model_name="userpreferencecategory",
            index=models.Index(
                fields=["user_preference"], name="pref_category_pref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreferencecategory",
            index=models.Index(fields=["category"], name="pref_category_cat_idx"),
        ),
        migrations.AddConstraint(
            model_name="userpreferencecategory",
            constraint=models.UniqueConstraint(
                fields=("user_preference", "category"),
                name="unique_user_preference_category",
            ),
        ),
    ]
