# Generated by Django 5.2.16 on 2026-08-24 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created_event", "Created event"),
                            ("updated_event", "Updated event"),
                            ("deleted_event", "Deleted event"),
                            ("verified_event", "Verified event"),
                            ("created_institution", "Created institution"),
                            ("updated_institution", "Updated institution"),
                            ("verified_institution", "Verified institution"),
                            ("promoted_user", "Promoted user"),
                            ("suspended_user", "Suspended user"),
                            ("reinstated_user", "Reinstated user"),
                            ("created_admin", "Created admin"),
                            ("removed_admin", "Removed admin"),
                        ],
                        max_length=64,
                    ),
                ),
                ("table_name", models.CharField(max_length=64)),
                ("record_id", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "admin activity log entry",
                "verbose_name_plural": "admin activity log",
                "db_table": "admin_activity_log",
                "ordering": ("-created_at",),
            },
        ),
    ]
