# Generated by Django 5.2.16 on 2026-08-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminactivitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Actor; null only for deliberate system actions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminactivitylog",
            index=models.Index(fields=["user"], name="audit_user_idx"),
        ),
        migrations.AddIndex(
            model_name="adminactivitylog",
            index=models.Index(fields=["table_name"], name="audit_table_idx"),
        ),
        migrations.AddIndex(
            model_name="adminactivitylog",
            index=models.Index(fields=["record_id"], name="audit_record_idx"),
        ),
        migrations.AddIndex(
            model_name="adminactivitylog",
            index=models.Index(fields=["created_at"], name="audit_created_idx"),
        ),
    ]
