# Generated by Django 5.2.16 on 2026-08-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["user"], name="registration_user_idx"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["event"], name="registration_event_idx"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["status"], name="registration_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_event_registration"
            ),
        ),
    ]
