# Generated by Django 5.2.16 on 2026-07-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier used by the frontend, e.g. an iconify name.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Shown on event cards. Falls back to a trimmed description.",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("college", "College"),
                            ("both", "High School & College"),
                        ],
                        default="both",
                        help_text="Who this event targets — used for both filtering and recommendations.",
                        max_length=20,
                    ),
                ),
                ("venue_name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                (
                    "location",
                    models.CharField(
                        help_text="City/region, e.g. 'Nairobi'. Used for the location filter.",
                        max_length=120,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0 means free.",
                        max_digits=10,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave blank for unlimited.", null=True
                    ),
                ),
                (
                    "external_registration_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional — if set, 'Register' sends users here instead of registering in-platform.",
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True, help_text="Public Supabase Storage URL."
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Curator boost — featured events rank higher in the feed.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="events.category"
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
    ]
