# Generated by Django 5.2.16 on 2026-08-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("organizers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                db_column="institution_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="organizers.institution",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                db_column="verified_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="category",
            field=models.ForeignKey(
                db_column="category_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_categories",
                to="events.category",
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="event",
            field=models.ForeignKey(
                db_column="event_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_categories",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="events.EventCategory",
                to="events.category",
            ),
        ),
        migrations.AddField(
            model_name="savedevent",
            name="event",
            field=models.ForeignKey(
                db_column="event_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="savedevent",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="school_level",
            field=models.ForeignKey(
                blank=True,
                db_column="school_level_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.schoollevel",
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategory",
            index=models.Index(fields=["event"], name="event_category_event_idx"),
        ),
        migrations.AddIndex(
            model_name="eventcategory",
            index=models.Index(fields=["category"], name="event_category_cat_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventcategory",
            constraint=models.UniqueConstraint(
                fields=("event", "category"), name="unique_event_category"
            ),
        ),
        migrations.AddIndex(
            model_name="savedevent",
            index=models.Index(fields=["user"], name="saved_event_user_idx"),
        ),
        migrations.AddIndex(
            model_name="savedevent",
            index=models.Index(fields=["event"], name="saved_event_event_idx"),
        ),
        migrations.AddConstraint(
            model_name="savedevent",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_saved_event"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_time"], name="events_start_time_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["end_time"], name="events_end_time_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_verified"], name="events_is_verified_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["institution"], name="events_institution_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["school_level"], name="events_school_level_idx"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="event_end_time_after_start_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="event_latitude_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="event_longitude_in_range",
            ),
        ),
    ]
