# Generated by Django 5.2.16 on 2026-08-24 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "logo_url",
                    models.TextField(
                        blank=True,
                        help_text="Supabase Storage URL for the logo.",
                        null=True,
                    ),
                ),
                ("location", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Set by an administrator after review."
                    ),
                ),
            ],
            options={
                "db_table": "institutions",
                "ordering": ("name",),
            },
        ),
    ]
