# Generated by Django 5.2.16 on 2026-08-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institutions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["slug"], name="institutions_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["verified"], name="institutions_verified_idx"),
        ),
    ]
